pub mod consolidation;
pub mod decay;
pub mod graph;
pub mod in_memory;
pub mod pattern;
pub mod persona;
pub mod skill;
pub mod storage;
pub mod store;
pub mod types;

pub use consolidation::{consolidate, detect_conflicts, resolve_conflicts};
pub use decay::{apply_decay_to_all, promote_memories, prune_below_threshold};
pub use graph::MemoryGraph;
pub use in_memory::InMemoryStore;
pub use pattern::{strengthen_co_activated, complete_pattern, CompletePatternArgs, CompletePatternResult};
pub use persona::extract_persona;
pub use skill::{detect_and_create_skill, find_skill};
pub use storage::RocksDbStore;
pub use store::MemoryStore;
pub use types::*;